# Reshaping ,view,stacking ,squeezing,and unsqueezing,view,permute

In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshape add extra dimension  ((((RESHAPE HAS TO BE COMPATIBLE WITH THE INPUT SIZE))))
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape,x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [ ]:
#CHANGE THE VIEW (((VIEW SHARES SAME MEMORY)))
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#CHANGING Z CHANGES X
z[:,0]=19
x,z

(tensor([19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]))

# STACK

In [ ]:
#STACK on top of each other
x_stacked=torch.stack([x,x,x,x])#dim=0 by default
x_stacked

tensor([[19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

# Torch Squeeze- removes all single dimension from the target

In [ ]:
x_reshaped,x_reshaped.shape,x_reshaped.squeeze(),x_reshaped.squeeze().shape

(tensor([[19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([1, 9]),
 tensor([19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([9]))

# Torch UnSqueeze- add dimension from the target

In [ ]:
x_squeezed=x_reshaped.squeeze()
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[19.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

# Torch.permute- rerturn a view of the original tensor with it's dimensions permuted or rearrange (Used for Images)

In [ ]:
x_original=torch.randn(size=(224,224,3)) #[height,width,color channels]
x_permuted=x_original.permute(2,0,1)#shifts axis 0->1 ,1->2 , 2->0  i.e   [Color channels, height, width]
x_original.shape,x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Tensor And Numpy

In [ ]:
import numpy as np
array=np.arange(1.0,9.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
tensor2=torch.arange(1.,9.)
array2=tensor2.numpy()
array2,tensor2

(array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

# REPRODUCIBILITY -Controlling sources of randomness

In [ ]:
RANDOM_SEED=42
# create 2 random tensors
torch.manual_seed(RANDOM_SEED)
a=torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
b=torch.rand(3,3)
print(a)
print(b)
print(a==b)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# GPU

In [ ]:
!nvidia-smi

Mon Jul  3 20:29:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor=torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu,tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
#!!!!!  If you use GPU you cant convert it to numpy since numpy doesnt work on gpu
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
tensor_back_on_cpu=tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])